export { useWindowStore } from './window-manager';
export { calculateTilingLayout, getSnapZones, detectSnapZone } from './window-manager';
export type { SnapZone } from './window-manager';
export { useAppStore } from './app-manager';
export { VFS, getVFS, IndexedDBProvider, OPFSProvider, isOPFSSupported } from './vfs';
export { NetProxy, getNetProxy, ProxyCache, defaultProxyConfig } from './net-proxy';
export type { ProxyConfig, ProxyRequestOptions, ProxyResponse, ProxyCacheEntry } from './net-proxy';
export { useWidgetStore } from './widget';
export { useIslandStore } from './island';
export { useNotificationStore } from './notification-center';
export type { NotificationEntry } from './notification-center';
export { registerKernelServices } from './register';
export { useDialogStore } from './dialog';
export { useClipboardStore } from './clipboard';
export type { ClipboardEntry } from './clipboard';
export { useHotkeyStore, useGlobalHotkey } from './hotkey';
export type { HotkeyBinding } from './hotkey';
export { usePowerStore } from './power';
export type { PowerAction, PowerEvent } from './power';
export { useSearchStore } from './search';
export type { SearchProvider, SearchItem, SearchCommand } from './search';
export { useDefaultAppsStore } from './default-apps';
export type { HandlerEntry, DefaultAppHandler } from './default-apps';
